# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestTest1register():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_test1register(self):
        # Test name: test1_register
        # Step # | name | target | value
        # 1 | open | / |
        self.driver.get("http://127.0.0.1:8000/")
        # 2 | setWindowSize | 1552x832 |
        self.driver.set_window_size(1552, 832)
        # 3 | click | linkText=Register |
        self.driver.find_element(By.LINK_TEXT, "Register").click()
        # 4 | click | id=id_first_name |
        self.driver.find_element(By.ID, "id_first_name").click()
        # 5 | type | id=id_first_name | client2
        self.driver.find_element(By.ID, "id_first_name").send_keys("client2")
        # 6 | click | id=id_last_name |
        self.driver.find_element(By.ID, "id_last_name").click()
        # 7 | type | id=id_last_name | client2
        self.driver.find_element(By.ID, "id_last_name").send_keys("client2")
        # 8 | click | id=id_email |
        self.driver.find_element(By.ID, "id_email").click()
        # 9 | type | id=id_email | client2@email.com
        self.driver.find_element(By.ID, "id_email").send_keys("client2@email.com")
        # 10 | click | id=id_phone_number |
        self.driver.find_element(By.ID, "id_phone_number").click()
        # 11 | type | id=id_phone_number | 0744111222
        self.driver.find_element(By.ID, "id_phone_number").send_keys("0744111222")
        # 12 | click | id=id_username |
        self.driver.find_element(By.ID, "id_username").click()
        # 13 | type | id=id_username | client2
        self.driver.find_element(By.ID, "id_username").send_keys("client2")
        # 14 | click | id=id_password1 |
        self.driver.find_element(By.ID, "id_password1").click()
        # 15 | click | id=id_password1 |
        self.driver.find_element(By.ID, "id_password1").click()
        # 16 | type | id=id_password1 | Second2#
        self.driver.find_element(By.ID, "id_password1").send_keys("Second2#")
        # 17 | click | id=id_password2 |
        self.driver.find_element(By.ID, "id_password2").click()
        # 18 | type | id=id_password2 | Second2#
        self.driver.find_element(By.ID, "id_password2").send_keys("Second2#")
        # 19 | click | css=.btn-primary |
        self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
        # 20 | click | id=id_username |
        self.driver.find_element(By.ID, "id_username").click()
        # 21 | type | id=id_username | client2
        self.driver.find_element(By.ID, "id_username").send_keys("client2")
        # 22 | click | id=id_password |
        self.driver.find_element(By.ID, "id_password").click()
        # 23 | type | id=id_password | Second2#
        self.driver.find_element(By.ID, "id_password").send_keys("Second2#")
        # 24 | click | css=.btn-primary |
        self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
        # 25 | click | linkText=Detalii |
        # self.driver.find_element(By.LINK_TEXT, "Detalii").click()
